import fs from "fs";
import path from "path";

// In production on Render the persistent disk is mounted at /uploads
export const uploadsDir =
  process.env.NODE_ENV === "production"
    ? "/uploads"
    : path.resolve(process.cwd(), "uploads");

export const CHUNK_SIZE = 1024 * 1024;

export interface FileMeta {
  id: string;
  name: string;
  size: number;
  mimeType: string;
  chunkCount: number;
  chunkSize: number;
  uploadedAt: string;
  chunkUrls: string[];
  expiresAt?: string;
  seedOnly?: boolean;
}

export function ensureUploadsDir(): void {
  if (!fs.existsSync(uploadsDir)) {
    fs.mkdirSync(uploadsDir, { recursive: true });
  }
}

// fileId is always a uuidv4() generated by this service (see routes/files).
// Reject anything else so a crafted fileId (e.g. "../../etc") can never be
// used to escape uploadsDir via path.join.
const FILE_ID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isValidFileId(fileId: string): boolean {
  return FILE_ID_PATTERN.test(fileId);
}

export function getFileDir(fileId: string): string {
  if (!isValidFileId(fileId)) {
    throw new Error(`Invalid fileId: "${fileId}"`);
  }
  const dir = path.join(uploadsDir, fileId);
  // Defense in depth: ensure the resolved path never escapes uploadsDir,
  // even if the regex check above is ever loosened or bypassed.
  const resolvedDir = path.resolve(dir);
  const resolvedRoot = path.resolve(uploadsDir);
  if (
    resolvedDir !== resolvedRoot &&
    !resolvedDir.startsWith(resolvedRoot + path.sep)
  ) {
    throw new Error(`Invalid fileId: "${fileId}"`);
  }
  return dir;
}

export function getMetaPath(fileId: string): string {
  return path.join(getFileDir(fileId), "meta.json");
}

export function getChunkPath(fileId: string, chunkIndex: number): string {
  if (!Number.isInteger(chunkIndex) || chunkIndex < 0) {
    throw new Error(`Invalid chunkIndex: ${chunkIndex}`);
  }
  return path.join(getFileDir(fileId), `chunk_${chunkIndex}.bin`);
}

export function saveMeta(meta: FileMeta): void {
  const dir = getFileDir(meta.id);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(getMetaPath(meta.id), JSON.stringify(meta, null, 2));
}

export function readMeta(fileId: string): FileMeta | null {
  if (!isValidFileId(fileId)) return null;
  const metaPath = getMetaPath(fileId);
  if (!fs.existsSync(metaPath)) return null;
  try {
    return JSON.parse(fs.readFileSync(metaPath, "utf-8")) as FileMeta;
  } catch {
    return null;
  }
}

export function isFileExpired(meta: FileMeta): boolean {
  if (!meta.expiresAt) return false;
  return new Date(meta.expiresAt) < new Date();
}

export function listAllFiles(): FileMeta[] {
  ensureUploadsDir();
  const entries = fs.readdirSync(uploadsDir, { withFileTypes: true });
  const files: FileMeta[] = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const meta = readMeta(entry.name);
    if (meta && !isFileExpired(meta)) files.push(meta);
  }
  return files.sort(
    (a, b) =>
      new Date(b.uploadedAt).getTime() - new Date(a.uploadedAt).getTime(),
  );
}

export function deleteFile(fileId: string): boolean {
  if (!isValidFileId(fileId)) return false;
  const dir = getFileDir(fileId);
  if (!fs.existsSync(dir)) return false;
  fs.rmSync(dir, { recursive: true, force: true });
  return true;
}

export function purgeExpiredFiles(): number {
  ensureUploadsDir();
  const entries = fs.readdirSync(uploadsDir, { withFileTypes: true });
  let count = 0;
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const meta = readMeta(entry.name);
    if (meta && isFileExpired(meta)) {
      deleteFile(meta.id);
      count++;
    }
  }
  return count;
}

export function splitAndSave(fileId: string, buffer: Buffer): number {
  const dir = getFileDir(fileId);
  fs.mkdirSync(dir, { recursive: true });
  let chunkIndex = 0;
  let offset = 0;
  while (offset < buffer.length) {
    const chunk = buffer.subarray(offset, offset + CHUNK_SIZE);
    fs.writeFileSync(getChunkPath(fileId, chunkIndex), chunk);
    chunkIndex++;
    offset += CHUNK_SIZE;
  }
  return chunkIndex;
}

export function buildChunkUrls(
  fileId: string,
  chunkCount: number,
  baseUrl: string,
): string[] {
  return Array.from(
    { length: chunkCount },
    (_, i) => `${baseUrl}/api/files/${fileId}/chunks/${i}`,
  );
}

export function generateSnippet(meta: FileMeta, baseUrl: string): string {
  return `(function() {
  var fileId = "${meta.id}";
  var fileName = ${JSON.stringify(meta.name)};
  var mimeType = ${JSON.stringify(meta.mimeType)};
  var chunkCount = ${meta.chunkCount};
  var baseUrl = ${JSON.stringify(baseUrl)};

  function downloadFile() {
    var promises = [];
    for (var i = 0; i < chunkCount; i++) {
      promises.push(
        fetch(baseUrl + "/api/files/" + fileId + "/chunks/" + i)
          .then(function(r) { return r.arrayBuffer(); })
      );
    }
    Promise.all(promises).then(function(chunks) {
      var blob = new Blob(chunks, { type: mimeType });
      var url = URL.createObjectURL(blob);
      var a = document.createElement("a");
      a.href = url;
      a.download = fileName;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }).catch(function(err) {
      console.error("FileSplit download failed:", err);
    });
  }

  document.querySelectorAll('[data-filesplit="${meta.id}"]').forEach(function(el) {
    el.addEventListener("click", downloadFile);
  });

  window.FileSplit = window.FileSplit || {};
  window.FileSplit["${meta.id}"] = { download: downloadFile, fileName: fileName };
})();`;
}
